services:
  secretsanta:
    image: secretsanta
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=${HOST}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - INPUT_FILE_PATH=/input.json
    volumes:
      - ./input.json:/input.json
      - ./.db/:/usr/src/app/.db/  
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: secretsanta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.com
      PGADMIN_DEFAULT_PASSWORD: a
    ports:
      - "8080:80"
    depends_on:
      - postgres
    restart: always

volumes:
  postgres_data: